import type { Metadata } from "next";
import localFont from "next/font/local";
import "../styles/globals.css";
import LenisScroll from "@/components/lenisScroll";

const Acorn = localFont({
  src: [
    {
      path: "../../public/fonts/Acorn-Light.ttf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/Acorn-Medium.ttf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/Acorn-Regular.ttf",
      weight: "normal",
      style: "normal",
    },
    {
      path: "../../public/fonts/Acorn-SemiBold.ttf",
      weight: "600",
      style: "normal",
    },
    {
      path: "../../public/fonts/Acorn-Bold.ttf",
      weight: "bold",
      style: "normal",
    },
  ],
  variable: "--font-Acorns",
});

const Planar = localFont({
  src: [
    {
      path: "../../public/fonts/GT-Planar-Light.otf",
      weight: "300",
      style: "normal",
    },
    {
      path: "../../public/fonts/GT-Planar-Medium.otf",
      weight: "500",
      style: "normal",
    },
    {
      path: "../../public/fonts/GT-Planar-Regular.otf",
      weight: "normal",
      style: "normal",
    },
    // {
    //   path: "../../public/fonts/GT-Planar-SemiBold.otf",
    //   weight: "600",
    //   style: "normal",
    // },
    {
      path: "../../public/fonts/GT-Planar-Bold.otf",
      weight: "bold",
      style: "normal",
    },
  ],
});

export const metadata: Metadata = {
  title: "Toluwani",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en" className={`${Planar.className} ${Acorn.variable}`}>
      <body className="overflow-hidden bg-[#EEF2FF]">
        <LenisScroll>{children}</LenisScroll>
      </body>
    </html>
  );
}
